### ISSUE TITLE
Need help installing oot3dhax using digital version of game.

### ISSUE THREAD

**Issue by TheProvider0** [yellows8/oot3dhax#101]
I need help on installing oot3dhax on my digital copy of oot. I've gotten very close to being able to get it installed on it. The error Im getting is shown in the pic. Any ideas on how to fix it? I'm using a New 3DSXL on ver 11.2.0-35 USA. I use smashhax to get into homebrew launcher. (and obviously I need a more convenient method of accessing homebrew) Sorry for the crappy quality
![20161130_180412](https://cloud.githubusercontent.com/assets/24284011/20781213/1183e320-b736-11e6-8081-afc854074993.jpg)

**Comment by yellows8** [comment]
Please do not ask about any installer not included with the starter-kit here(+ run the game at least once).

**Comment by TheProvider0** [comment]
@yellows8 I'm using an offline installer. It requires me to have a payload already inside the correct folder path. This installer is almost identical. So if you could help me, please do.

**Comment by TheProvider0** [comment]
@yellows8
