### ISSUE TITLE
installing save01.bin Error FFFFFFFF

### ISSUE THREAD

**Issue by Eduens** [yellows8/oot3dhax#102]
http://i.imgur.com/R6fFK2d.jpg

What does that mean?

**Comment by TheProvider0** [comment]
Are you trying to install it to the digital version of the game? If so, we've got the same problem here. When I opened up an issue here, yellows8 just said to not talk about an installer that isn't in the starter pack. I had an offline version of the installer so they're practically identical. I'm just not sure why he wouldn't help me.

**Comment by yellows8** [comment]
"I'm just not sure why he wouldn't help me." <- Not my sw to support obviously...

**Comment by TheProvider0** [comment]
@yellows8 What do you mean by  'Not my/our sw to support' ?

**Comment by TheProvider0** [comment]
@yellows8 Ok, I get it. It was a nooby move to comment whatever I commented. I'm sorry, ok? But you didn't give me much help on how to fix my problem. If you could help either me or Eduens. That would be wonderful. Again, I'm sorry.

**Comment by yellows8** [comment]
"But you didn't give me much help on how to fix my problem." <- I kinda did a while ago & no response...

**Comment by TheProvider0** [comment]
@yellows8 I said in my issue I was using an offline installer that's almost identical to the one that's included in the hbl starter. It requires a payload inside the directory with the installer. This offline installer was made for the people having problems downloading the payload with the one that's included in the starter. All you said was not to ask for help with a program that's not included in the starter.

**Comment by yellows8** [comment]
" All you said " no

**Comment by TheProvider0** [comment]
@yellows8 I don't understand. You've only commented to my issue once.

**Comment by yellows8** [comment]
Try reading the comment again.

**Comment by TheProvider0** [comment]
@yellows8 Are you trying to say I should find the forum of where my offline installer came from and ask for help there?

**Comment by yellows8** [comment]
Keep it in the original issue. https://github.com/yellows8/oot3dhax/issues/101#issuecomment-264089952 (The actual help in that comment was never replied to)

**Comment by TheProvider0** [comment]
@yellows8 Oh crap. I didn't know there was such a thing. I'm sorry man, I'll go check it out. I'm new to how github works so I didn't realize this.

**Comment by TheProvider0** [comment]
@yellows8 I'm really stupid. Arnt I?

**Comment by yellows8** [comment]
@TheProvider0 If that fixed it close your original issue.

**Comment by TheProvider0** [comment]
@yellows8 I have already ran the game atleast once. I'm closing my issue even though I never got it fixed.
