### ISSUE TITLE
error going into home menu without reboot

### ISSUE THREAD

**Issue by nico403** [yellows8/oot3dhax#103]
i'm on 11.0 o3ds 
i use oot3dhax and as said in the title the homebrew screen stuck for a while when I try to go to homemenu
an I use the latest starter kit 
hope you will help me

**Comment by yellows8** [comment]
Huh?

**Comment by nico403** [comment]
I boot homebrew launcher on my console with oot3dhax 
I want to run ctr httpwn and return to homemenu and access eshop
Previously it was working before I install the gridlauncher 
thats when I wanted to reinstall homebrew then it works but don't reboot into homemenu 
sorry I'm french

**Comment by yellows8** [comment]
Use the original hbmenu then...

**Comment by nico403** [comment]
I've install the original homebrew without gridlauncher

**Comment by yellows8** [comment]
"don't reboot into homemenu" Be more specific.

**Comment by nico403** [comment]
I press start button and x button

**Comment by yellows8** [comment]
If it hangs at ret2menu then you have menuhax installed....

**Comment by nico403** [comment]
thanks a lot !
