### ISSUE TITLE
A question. (Please delete if it doesn't belong)

### ISSUE THREAD

**Issue by l0rd0ct0d0rk** [yellows8/oot3dhax#106]
I managed to pull everything off successfully, using 11.2.0.35U, and I'm wondering if there's any way to add the homebrew channel launcher to the home menu, like the wii used to have, or will I always have to load the Hax save every time I want to access the homebrew channel? Once again, I'm sorry if this doesn't belong.  Thanks in advance.

**Comment by yellows8** [comment]
Only with "CFW".

**Comment by l0rd0ct0d0rk** [comment]
Thanks.
