### ISSUE TITLE
OoT3dHax not working.

### ISSUE THREAD

**Issue by xBeksimx** [yellows8/oot3dhax#107]
Hello so i am on 11.2.0-35.U the issue is i have gone through every single step multiple times, Gotten assistance from the 3dshacks community. and no one can figure out why it is not working. either we are all missing something obvious. or something isnt right... i am using the powersaves method as a main entry point for homebrew. below i will link images to showcase that all the files are in fact to the best of my knowledge and the 3dshacks community that this is correct.

http://imgur.com/a/YXp6c

Any help would be much appreciated as no one in the 3dshacks discord can see what is wrong.

**Comment by yellows8** [comment]
Just press A once it finishes loading & make sure you're using this one -> https://github.com/yellows8/oot3dhax/releases/latest

**Comment by xBeksimx** [comment]
yeah i can run around and i am using latest. i have spammed every button possible and i get nowhere. still just running around hyrule.

**Comment by xBeksimx** [comment]
Member of 3dshacks sent me a save file he downloaded and it worked... turned out the save i got from the latest just didn't work... i guess partially corrupt? lol
