### ISSUE TITLE
load payload from SD (or partial)

### ISSUE THREAD

**Issue by jankcat** [yellows8/oot3dhax#11]
I am sure you thought of this, but I was pondering options to allow a save file on the device beyond the launcher save file, so that the game is still playable.

Just going to mention them, in case the thought was never tossed your way.
- Load the payload.bin file from SD instead of the cart.
- Load a partial payload, and load the rest from cart

Like I said, I do not know if these are possible, but thought I would throw them out in the open.
Also, I have only ever done managed development, so I probably would not be much help, but I'll do my best to learn so that I don't suggest things that wont work again ;)

**Comment by smealum** [comment]
OOT does not have access to the SD card so those aren't possible without significant effort.

**Comment by jankcat** [comment]
Well, thanks for the fast reply!

**Comment by jankcat** [comment]
@smealum here is another thought...
Could a launcher/enhancer like HANS redirect the game to the SD card when looking for saves?

**Comment by yellows8** [comment]
#22
