### ISSUE TITLE
Updated to latest and get an error

### ISSUE THREAD

**Issue by Stepghad** [yellows8/oot3dhax#114]
I used the installer to update to the latest OOTHAX on my N3DS 11.2.0-35-U. The savegame loads fine but when I press A to start the HAX I get sent to the 3ds home menu and it tells me an error has occurred and the system must be reset.

**Comment by GamingAnimator** [comment]
same issue, im noticing that this is a common issue

this might help read this its from another post

https://github.com/yellows8/oot3dhax/issues/121
