### ISSUE TITLE
"Homebrew Ropbin is ready" Then nothing happens

### ISSUE THREAD

**Issue by lachie12435** [yellows8/oot3dhax#115]
Please help me, I was able to use homebrew just fine before a couple days ago, now whenever I choose to open hombrew it says "hombrew ropbin ready..." then closes back to the home screen, I have tried multiple times but still nothing happens. Please can someone help me!!!!

**Comment by GamingAnimator** [comment]
im having the same issue

read this

https://github.com/yellows8/oot3dhax/issues/121
