### ISSUE TITLE
When will the OOT haxsaves update come out? For EU and Asia

### ISSUE THREAD

**Issue by Ripbull59** [yellows8/oot3dhax#116]
Compatible with 11.3.0-36

THx
![post5_e_26624_9221](https://cloud.githubusercontent.com/assets/25750814/22896121/3321197a-f21f-11e6-853d-3b31ea2c4188.png)

**Comment by yellows8** [comment]
"Asia" README

**Comment by Ripbull59** [comment]
Ok cool for asians. And for Europe and Japan? Thank you for your work.

**Comment by yellows8** [comment]
later

**Comment by Ripbull59** [comment]
Ok. Thanks again

**Comment by kamikazilucas** [comment]
i dont get how to use sploit installer
