### ISSUE TITLE
OOT3DHAX Payload for New 11.3.0.36U

### ISSUE THREAD

**Issue by Sephious** [yellows8/oot3dhax#119]
Is there a new payload collection that I am unaware of. I believe the 11.3.0.36U firmware requires a POST5_U_27648_USA_9221.bin or N3DS_U_27648_USA_9221.bin, but I can not find either of these in the list of currently available payloads.

**Comment by bournejason** [comment]
yeah, seems the latest release cannot work any more with 11.3.0.36U, I'm waiting for a new payload too...

**Comment by lunarFlight** [comment]
go to #121 , save image there for US and EU 11.5
