### ISSUE TITLE
OoT3D Sploit Installer Failing to Install Payload 

### ISSUE THREAD

**Issue by OTFree** [yellows8/oot3dhax#12]
Forgive me, I know the Sploit Installer is partially credited to Smea, but I didn't know where else to report the issue. I downloaded the most recent installer from the Homebrew Starter kit, and I tried to install Oot3DHax on my N3DSXL (v. 9.9.0.26 USA) in the second slot. I tried using both Ironhax + Menuhax to run the installer, and I have a steady internet connection, so I know that's not the issue. I'm using Ocarina of Time 3D US v1.0 game cart if that helps. Basically, it seems to download the payload just fine, but when installing, I get; 

"Looks like something went wrong. :( 
Current Status:
Failed to install payload
Error code: C86044CD"

I've tried to run it again multiple times, but I keep getting the same error.

**Comment by yellows8** [comment]
https://github.com/smealum/sploit_installer/issues/2

**Comment by OTFree** [comment]
Sorry about that, I appreciate the quick reply though and thank you for the link :)

**Comment by phase** [comment]
@OTFree If you have any other problems with the _**installer**_, you can report an issue on the [oot3dhax_installer](https://github.com/phase/oot3dhax_installer) repository.
