### ISSUE TITLE
N3DS_E_26624_9221 support

### ISSUE THREAD

**Issue by kamikazilucas** [yellows8/oot3dhax#120]
the newest download only goes up to 25600 in europe , can you update it

**Comment by Mclaneinc** [comment]
Any news on this please, last payloads Powersaves just cause a crash sadly...Thanks

**Comment by Sal91** [comment]
Any news?

**Comment by GamingAnimator** [comment]
this might help

https://github.com/yellows8/oot3dhax/issues/121

**Comment by lunarFlight** [comment]
go to #121 , save image there for US and EU 11.5
