### ISSUE TITLE
Homebrew ropbin is ready... then homescreen?

### ISSUE THREAD

**Issue by Seal-Space** [yellows8/oot3dhax#122]
so i downloaded all the stuff and I got the ropbin file: POST5_U_26624_usa_9221 and chose the save file: POST5_U_26624_usa_9221

are these the correct files or is something wrong? my 2ds firmware is 11.4.0-37U

**Comment by FalcoMicky** [comment]
I have this exact same problem too, with 11.4.0.37E. Tried installing HB twice but both attempts resulted in a sudden homescreen. Using a New 3ds XL.

**Comment by CaptainPancake** [comment]
That happens when you aren't using the correct save-payload. The one for 11.4 hasn't come out yet; all we can do is wait.
