### ISSUE TITLE
can't load homebrew ver.11.0.0-33u

### ISSUE THREAD

**Issue by RustyBallz** [yellows8/oot3dhax#123]
I've copied over all the correct files to my sd card but when I try to play the '<3 nedwill 2016" song I get booted back the the home screen and a message displays 'An error has occurred, forcing the software to close. The system will now restart'

All I've found is '11.0.0.33 is supported with the June 26, 2016, oot3dhax release builds.' but I have no idea what this means.

if anybody can help it would be greatly appreciated.

**Comment by Seal-Space** [comment]
ok, are you using a powersaves device?

**Comment by RustyBallz** [comment]
I don't quite understand the question. I bought a 2DS yesterday unpacked it and attempted to load homebrew on it.

**Comment by Seal-Space** [comment]
ok and the firmware is 11.0.0-33
 what is the letter at the end? Example: 11.4.0-37U

**Comment by Seal-Space** [comment]
wait '<3 nedwill 2016 is soundhax not oot3dhax

**Comment by RustyBallz** [comment]
11.0.0-33U

**Comment by Seal-Space** [comment]
Ok so are you trying to install soundhax or oot3dhax, both are different things

**Comment by RustyBallz** [comment]
I followed https://3ds.guide/homebrew-launcher-(soundhax) exactly. Once I get to step 10 the screen will flash green then red and then I get booted back to home screen with a message 'An error has occurred, forcing the software to close. The system will now restart'

**Comment by RustyBallz** [comment]
I've just come to the realization that this section is not for soundhax

**Comment by Seal-Space** [comment]
ya but i can help over on nedwills page k?

**Comment by RustyBallz** [comment]
yes please  I"ll submit the issue there

thanks
