### ISSUE TITLE
oot3dhax 11.4??

### ISSUE THREAD

**Issue by AgentScarlet** [yellows8/oot3dhax#125]
will oot3dhax be able to be installed on 11.4 and work?? i just was curious for the most part

**Comment by GamingAnimator** [comment]
im not sure where the issue lies in, im able to get it up where you press "A" and it looks for ropbin but it crashes and sends me back to main menu of new 3ds xl, says "an error occurred"

**Comment by GamingAnimator** [comment]
from my understanding home brew website says that they are up date on there info, also they say that thier payload is up to date, only thing that seems a bit late is the save file is from January. i hope we can find help

**Comment by GamingAnimator** [comment]
i believe i found the issue

https://github.com/yellows8/oot3dhax/issues/121

**Comment by Korados** [comment]
Sorry but what is actually happening here? Does yellows8 still work on new saves or not? 3dbrew.org shows that oothax is still working with 11.4, so I updated and tried it, just to see my 3DS go back to the main menu when I try to start the homebrew launcher.
