### ISSUE TITLE
11.4.0-37!? Menu Crash Error

### ISSUE THREAD

**Issue by YungEvil** [yellows8/oot3dhax#128]
I USE EVERY LAST BIN INTO ZELDA INTO POWERSAVES AND ALL IT SHOWS IS HOMEBREW TRYING TO LOAD AND SAYS "ROPBIN" AND CRASH AND SAYS"ERROR PLEASE SAVE THE SOFTWARE AND RESTART I'M VERY PISSED. Can Anyone help plz!?

**Comment by joe-pacheco** [comment]
Three are no saves for the latest firmware
