### ISSUE TITLE
When will the new Powersaves files for OOT3DHax be released for 11.5.0-38

### ISSUE THREAD

**Issue by PlatinumLord** [yellows8/oot3dhax#129]
I am really irritated! I tried to use OOT3Dhax on my New 3DS XL when 11.5.0-38U was released and all of the sudden, it keeps going back to the home menu! I did all of the steps and nothing works since there's no save file for 11.5.0-38 saved for this. Sorry if I sound frustrated but I would like to know if there will ever be a new file that all frustrated homebrew users like me can use to make OOT3Dhax work again? Thank you!

**Comment by AJHahm** [comment]
I have the same problem!

**Comment by AJHahm** [comment]
i think yellows8 is still working on 11.4 save files. [https://github.com/yellows8/oot3dhax/issues/128](url)

**Comment by jnrepo** [comment]
https://github.com/yellows8/oot3dhax/issues/121
