### ISSUE TITLE
N3DS 8.1J

### ISSUE THREAD

**Issue by Soundtoxin** [yellows8/oot3dhax#13]
Is there any way you could support 8.1J firmware on the New 3DS? It's a fairly common firmware on older models of the New 3DS from Japan and it didn't come with a browser. It really puts people in a sorry state as far as trying to setup custom firmware and such. I got a japanese copy of ocarina of time 3D, but it seems that I'm still screwed without either a gateway, sky3ds, or japanese cubic ninja (costs over $100).

**Comment by ihaveamac** [comment]
oot3dhax runs the *hax (or ninjhax) payload, but both 1.x and 2.x only support 9.0+ on New 3DS. I think 1.x also requires a browser.

**Comment by yellows8** [comment]
This is only payload-related, not oot3dhax related. As said above only >=v9.0 system-versions are supported by the *hax payloads.
