### ISSUE TITLE
POST5_E_27649_9221 with POWERSAVES V1.5.1 not working

### ISSUE THREAD

**Issue by AndreS8Shok** [yellows8/oot3dhax#130]
tried with both cardids_45fe009000000000 and cardids_c2fe009000000000

I do:
1_backup OOT save with powersave
2_copy POST5_E_27649_9221 into powersave backup directory
3_rename game backup into something else
4_rename POST5_E_27649_9221 with the backup old name
5_recover backup via powersave

tried also deleting all save data from game on boot with X+Y+A+B durin 3DS screen and retried but don't work.

I'm on 2DS 11.5.0-38E

but even if i do this with both cardids, it still says "Save data corrupted" and delete save files.
Any suggestions? :/ i always used oot3dHax with previous firmwares and always worked but this times it give me this problem :/

**Comment by edgelord9000** [comment]
The same problem occurs on my NEW 3ds 11.5 EUR Tried the exact same things and got the same results.

**Comment by yellows8** [comment]
Save builds are broken :(

**Comment by AndreS8Shok** [comment]
So we need to build the save by ourself? hmmm

**Comment by yellows8** [comment]
updated https://github.com/yellows8/oot3dhax/releases/tag/08-21-17

**Comment by AndreS8Shok** [comment]
Thanks Man!
cardids_c2fe009000000000 worked for me! now putting Otherapp and see what happens! ^^

EDIT: all working! ^^ thankyou very much ^^
