### ISSUE TITLE
Only Pulls Up Region Lock

### ISSUE THREAD

**Issue by pokemaster1226** [yellows8/oot3dhax#16]
I have the U.S. files, and I get into homebrew fine (by using Powersaves to create the back up, and eventually restoring it) but whenever it boots up the only thing that displays is region lock. I don't have another hax method (I had Tubehax but it was patched) to install it like that, but on the homebrew page it said this was the "latter" so I took this as that it is indeed possible. Any help is appreciated :)

**Comment by yellows8** [comment]
Uh, sounds like your SD /3ds directory is empty ....

https://smealum.github.io/3ds/

**Comment by pokemaster1226** [comment]
THANK YOU SO MUCH!!!
