### ISSUE TITLE
After Installing OoT3d hax in Homebrew...

### ISSUE THREAD

**Issue by pokemaster1226** [yellows8/oot3dhax#17]
It wont boot homebrew up. It changed the save to "Haxx*****..." and then every time I try to get into Homebrew it crashes (presumably) and I am taken to the home menu with the message "An error occurred." I had an issue a couple of hours ago but it got resolved, but after that I could boot into Homebrew just fine. I was told to install OoT3d from Homebrew (which I did in the first slot) but after this happens. I know I must have done something wrong in the installation ( I might have not needed to do it at all...), thanks for you're help so far :)

**Comment by ihaveamac** [comment]
you probably picked the wrong firmware version in the installer.

**Comment by phase** [comment]
Which installer and firmware are you using?

**Comment by pokemaster1226** [comment]
That's probably the case, lol. Thanks you guys!
