### ISSUE TITLE
what save file do I use 

### ISSUE THREAD

**Issue by serventseaslug** [yellows8/oot3dhax#18]
I have 10.3.0-28U and both the power save and r4i save dongle but can't tell what save I should be installing into my game http://prntscr.com/9i67rf  http://prntscr.com/9i67wf

**Comment by yellows8** [comment]
https://github.com/yellows8/oot3dhax#installation "If you don't know what the cardids for your gamecard are(these are included with what are commonly called "gamecard-unique headers"), just try either directory until one of them works without the game triggering a savedata-corruption error at boot."

**Comment by serventseaslug** [comment]
https://www.youtube.com/watch?v=zeHoHjn1_rQ this is whats going on.

**Comment by yellows8** [comment]
Please double-check your console system-version. I *know* it works fine with v10.3 Old3DS.

**Comment by serventseaslug** [comment]
http://prntscr.com/9i6ppq thats what I have, I remember it working with the iron fall game and I don't remember updating it since then

**Comment by yellows8** [comment]
Your system definitely is Old3DS, right?

**Comment by serventseaslug** [comment]
yea
