### ISSUE TITLE
Error code: C86044CD

### ISSUE THREAD

**Issue by plumpudding** [yellows8/oot3dhax#19]
So sorry to interrupt you again. I wanted to install it using the installer included in the starter kit. It says "Installing payload" and "Looks like something went wrong" shortly after that. On the bottom there is the error code mentioned in the title. I have updated to FW 10.3.0-28E and am using an old 3ds xl. I am using menuhax to run the installer.

**Comment by yellows8** [comment]
https://github.com/smealum/sploit_installer/issues/2

**Comment by plumpudding** [comment]
I can't try atm but I expect it to work. Thanks!
