### ISSUE TITLE
i am having a bit of trouble getting things started.

### ISSUE THREAD

**Issue by thegaunt007** [yellows8/oot3dhax#20]
I believe i've put everything on the SD card that is required. that includes all the saved image data. I start up the game but my save files remain the same. Would you happen to have an idea what is going on? or do you need more information to help with the issue?

**Comment by yellows8** [comment]
I guess you're not writing the saveimage correctly then.

**Comment by thegaunt007** [comment]
how do i write it correctly?

**Comment by yellows8** [comment]
You didn't really describe how you wrote the saveimage.

**Comment by thegaunt007** [comment]
i dragged and dropped them onto the SD card root.

**Comment by phase** [comment]
Putting it on the SD card doesn't write it to the card, you have to use an installer or save manager.
