### ISSUE TITLE
Payload compression

### ISSUE THREAD

**Issue by PokeAcer549** [yellows8/oot3dhax#22]
Would it be possible to compress the hax 2.5 payload, so that more than just one save is possible?

**Comment by yellows8** [comment]
I'm not really interested in implementing anything oot3dhax-specific for that(probably not enough space in the actual savefile anyway).

**Comment by yellows8** [comment]
https://github.com/smealum/ninjhax2.x/commit/f3864a3b221b809c0df5cf54d9a6e4f3c94b7eca
