### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lostinhiding** [yellows8/oot3dhax#23]
Hello. My end goal here to be able to enable homebrew on my new 3ds firmware 9.9.0-26U. (Specifically Retroarch) I followed a link at redit to the following flowchart:

http://imgh.us/hax_1.svg

It makes it seem like it is possible to get homerew working on a new 3ds using a sky3ds+ flash card?

I'm trying to use the oot3dshax. I don't really understand what to do or how it works?

I've downloaded the files hosted by this github. But, I'm not sure what to do next. Is there possibly a tutorial somewhere that I should be following?

Looking at the contents of the file I download from here. I don't really understand the different between a powersave and the other folder. There is also a division called "card Ids." Is there someway to learn about what that means? I'm not certain how to find my card ID? Lastly the individual files seem to have a naming convention that goes above my head. For instance, some are labeled N3DS_U_XXXXX_XXXXX
while others are labeled POST5_U_XXXXX_usa_XXXX. Is there anyway to narrow down which file I should use as opposed to exhaustively trying them all?

--Thank you

**Comment by yellows8** [comment]
README

**Comment by lostinhiding** [comment]
Hello yellows8,

Thank you for you expedient reply. I hope my first message make me sound completely dumb. I did read the README.

To be more specific I am lost in the Instillation section of the README.

Raw save-images which can be written to the gamecard savedata flash are contained in the oot3dhax release-archive. The "saveimages" directory is for raw 0x20000-byte saveimages, while "saveimages_powersaves" is for Datel Powersaves. Those directories contain two sub-directories, each for a different cardid set. If you don't know what the cardids for your gamecard are(these are included with what are commonly called "gamecard-unique headers"), just try either directory until one of them works without the game triggering a savedata-corruption error at boot. These directories then contain sub-directories for each game region. The saveimage files under those region directories have the same filename as the payload contained in the savedata, you can use the filename from this to determine which saveimage filename to use: https://smealum.github.io/3ds/#otherapp


The saveimage files under those region directories have the same filename as the payload contained in the savedata

I am using a Sky3ds+. The name of my rom image is "3DS0033 - The Legend of Zelda_ Ocarina of Time 3D.3ds" The name of my save data is "3DS0033 - The Legend of Zelda_ Ocarina of Time 3D.sav"

This does not match any of the files provided. LoL.

Is the Oothax compatible with the Sky3ds+ flashcard?

**Comment by yellows8** [comment]
"This does not match any of the files provided. LoL." Try *reading* again(if you can't, then go elsewhere for warezcard support).
