### ISSUE TITLE
Is my firmware too new?

### ISSUE THREAD

**Issue by CyberAly** [yellows8/oot3dhax#24]
Hello,

I downloaded the otherapp savedata for my firmware version from The Homebrew Launcher's website, but it doesn't match anything in the powersaves directory for my region.

The filename I need is N3DS_E_24576_9221, my firmware version is 10.6.0-31E. I am using a New 3DS from the UK.

I assume the problem is that my firmware is too new to work with this hack yet? I only recently started taking an interest in hacking my 3DS so until now I was keeping up to date.

Thanks for any help you can give, and thanks for making this hack.

**Comment by yellows8** [comment]
"yellows8 released this Jan 25, 2016" *cough*

Didn't get around to building saveimages for the latest \*hax payloads yet.

**Comment by CyberAly** [comment]
I didn't know when my firmware version was released.

ANYWAY WHATEVER i'l just wait a while.

Thanks.
