### ISSUE TITLE
no idea

### ISSUE THREAD

**Issue by megapete4** [yellows8/oot3dhax#25]
I'm getting homebrew set up on my "NEW" 3ds xl with the 10.6 update through the Zelda ocarina of time hack, I did everything the directions say, but when its booting up, it stops at the red page on the bottom screen and just freezes and I have to reboot my system

**Comment by yellows8** [comment]
Did you extract the starter-kit to SD?

**Comment by megapete4** [comment]
Yes, I did everything, still nothing

**Comment by megapete4** [comment]
It can work on my 2ds but I've got more important stuff on the 3ds
