### ISSUE TITLE
Zelda oot region four

### ISSUE THREAD

**Issue by sebsrizzo** [yellows8/oot3dhax#3]
Hi, i love your work in the 3ds scene and i would like to ask you a favor, could you please please compile zelda oot region four? Nobody has compiled it and i dont know how to do it, please it would be awesome, i really want to use it

**Comment by yellows8** [comment]
I assume you mean a raw savedata flash-image for writing with a gamecard USB dongle / etc.

The way to generate a proper image is to use a 3DS to write the image. But doing that for {3 oot3dhax regions} * {2 cardID sets} * {all the different regionFOUR builds with payload.bin} is a lot of images + effort.

**Comment by sebsrizzo** [comment]
Yeah i would like a save , i thought that region four support for zelda oot was complete thats why i was asking  for it, my zelda oot catridge is from Japan. Thanks

**Comment by yellows8** [comment]
The source code for it is complete.

I guess you don't know the 4-byte cardID for that gamecard?

**Comment by sebsrizzo** [comment]
Sorry i dont know it, Is it important?
My gamecard has this:
Lna-ctr-aqej-jpn
Aqejx10134

**Comment by yellows8** [comment]
What exactly would you use for writing the save-image if you had one?

**Comment by sebsrizzo** [comment]
My friend has a 6.x 3ds, i think i could inject the save with gateway restore option, he doesnt have a gateway card so i can not inject it with a dev app. If that doesnt works i think i should get a r4i dongle

**Comment by sebsrizzo** [comment]
What would you recommend me to write the save? I think rxtools has a injection feature

**Comment by yellows8** [comment]
"I think rxtools has a injection feature" <- I'm not familiar with how rxtools handles it.

**Comment by sebsrizzo** [comment]
Could you please share a jpn save? If you need information or help i would try to give it to you

**Comment by yellows8** [comment]
It's not really possible for me to upload just one saveimage, without knowing your cardID. And it sounds like you have no way to get it either.

**Comment by sebsrizzo** [comment]
Could you tell me how i can get my card id, maybe i can find a way to get it.

**Comment by yellows8** [comment]
Oh actually, you can get it from the data @ 0x1000 in a rom-dump /w GW(it's somewhere starting there, don't remember the exact offset).

**Comment by profi200** [comment]
You *need* a way to import the savegame fs (Currently only SaveDataFiler.). RAW savegames will not work/are too complicated.
And also i think he will not port regionFOUR to this. There is not enough demand for it.

**Comment by sebsrizzo** [comment]
Thats great, i will try to dump it with my friends 3ds and then i will open it in my computer

**Comment by yellows8** [comment]
"And also i think he will not port regionFOUR to this." It's already supported...

**Comment by profi200** [comment]
Since when? Thought that's CN-only.

**Comment by yellows8** [comment]
https://github.com/smealum/regionFOUR/commit/a95e31a8bb8e098624ce442c091d6b78cc5b3e46

**Comment by sebsrizzo** [comment]
Card id is the same as the header?

**Comment by yellows8** [comment]
It's stored in the so-called "header".

**Comment by sebsrizzo** [comment]
Excellent
I extracted my header with a tool and i got this
8E 9C 5A A2 58 15 D9 BC A1 9D 38 93 FF 31 8E 25 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
C2 FE 00 90 00 00 00 00 FF FF FF FF FF FF FF FF

**Comment by yellows8** [comment]
My codebase currently doesn't have anything implemented for accessing the raw flash image *on* the latest FIRM(patch from older FIRM isn't implemented). So I can't easily do anything with your saveimage right now.

**Comment by sebsrizzo** [comment]
Oh that is too bad but thanks anyway

**Comment by sebsrizzo** [comment]
Do you think that using save data filer will help?

**Comment by yellows8** [comment]
"Do you think that using save data filer will help?" <- Writing to the savedata FS using FSUSER is exactly what the README says to do, which is what that tool does.

**Comment by sebsrizzo** [comment]
If i have a 6.x 3ds, my game card id and save data filer whats else do i need?

**Comment by yellows8** [comment]
cardID doesn't matter with savedatafiler. Since you can use *filer, you could just build oot3dhax+regionFOUR yourself.

**Comment by sebsrizzo** [comment]
The problem is i dont know hot to build it, i have alredy installed savedatafiler in the 6.x 3ds. Sorry for bothering you is just that i want to use region four in my jap N3ds.

**Comment by sebsrizzo** [comment]
Well now the 3ds is 4.x ( i downgraded the console because the new rxtool version doesnt supports 4.5+ consoles)

**Comment by yellows8** [comment]
"now the 3ds is 4.x" In that case you can just use other things for region-free.

**Comment by sebsrizzo** [comment]
That console is from my friend, i want to use zelda oot region four in my 9.8 n3ds

**Comment by yellows8** [comment]
Write the contents of this into your oot3d savedata FS: https://dl.dropboxusercontent.com/u/20520664/regionFOUR_oot3d_jpn_new3ds_v98.zip

**Comment by sebsrizzo** [comment]
Wow thanks a lot, its working perfect. You re the best 3ds hacker, you are patient and really really helpful once again thanks a lot :) http://pho.to/9Tawx

**Comment by yellows8** [comment]
Strange, top-screen background is supposed to be black(and I even tested this build). Oh well I guess.
