### ISSUE TITLE
System Update 10.7

### ISSUE THREAD

**Issue by livecat** [yellows8/oot3dhax#31]
Are in the rawsavegameimages a data for a new 3ds with the system version 10.7 ?

I tryed the last but it didnt worked out for me ?

I have the same problemes as megapete4

**Comment by yellows8** [comment]
v10.7 is identical to v10.6 for the \*hax payloads. Be more specific if you're having issues.

**Comment by livecat** [comment]
so what i tryed is using the latest EU rawsaveimages data for the n3ds, but I only came thourgh the red screen ?

**Comment by yellows8** [comment]
Did you extract starter-kit to SD root with the SD properly inserted?

**Comment by livecat** [comment]
Yes I did.

**Comment by livecat** [comment]
Doesn't feels good buying a for 30€ a powersave + the oot and doesnt get it to work.

**Comment by yellows8** [comment]
Were you using homebrew on <v10.6 fine before?

**Comment by livecat** [comment]
No

**Comment by yellows8** [comment]
Can you verify that sdmc:/boot.3dsx exists with the same filesize from the starter-kit?

**Comment by livecat** [comment]
Uhm should sent u or in the forum a video ?

**Comment by yellows8** [comment]
Perhaps but that doesn't answer the previous message either.

**Comment by livecat** [comment]
So I tryed it again and my game says the score is faulty so what you say to this ?

**Comment by yellows8** [comment]
"score(s)" Huh?

**Comment by livecat** [comment]
"files" dont know which word is right for describing this

**Comment by kitling** [comment]
At risk of necro, and of not helping anyone... ._.

So, @livecat, what you were saying is that it said that the save files were corrupted, so it deleted them, I think? Do you have a physical cartridge, or did you buy it off the eShop? How did you inject the save? By using another 3ds with homebrew, or a powersaves device?

If you bought it off the eShop, I think you're out of luck, as you'd need homebrew on that device already to inject the save, which I guess you don't have.

If you bought a physical cartridge, attempt to re-inject the save, and tell us whether that solved the issue or not. Please also tell us how you are injecting it, so we can help determine if there is a mistake in the process somewhere.

But... somehow I don't think you're going to read this, as you probably stopped checking little under a month ago. Ah well. ._.
