### ISSUE TITLE
"The home menu robin is ready" 

### ISSUE THREAD

**Issue by lukeycat** [yellows8/oot3dhax#33]
i get that message after triggering the haxx by pressing items then i am sent back to the home screen i am running unmodified 10.7.0.32U on old3ds please help me i have been trying to install home menu hax for months using every different method i could find to no avail

**Comment by yellows8** [comment]
What .sav filename are you using?

**Comment by lukeycat** [comment]
it was a bin not a sav i put it on my cart using action replay power save i believe its name was ND3S_U_11272_8203 at least that is what action replay was calling it

**Comment by yellows8** [comment]
ND3S_U_24578_9221 is the right one.

**Comment by lukeycat** [comment]
I couldn't find that bin file within my zip file. could you give me a link to the right zip?

**Comment by yellows8** [comment]
POST5_U_24578_usa_9221 then.

**Comment by lukeycat** [comment]
that is the file i meant in my last comment it still did not work

**Comment by yellows8** [comment]
Try running sploit_installer from starter-kit via browserhax since you're on <v10.6 anyway.

**Comment by lukeycat** [comment]
crap. i accidentally wrote 10.5 on my first post. i am on 10.7

**Comment by yellows8** [comment]
POST5_U_25600_usa_9221

**Comment by lukeycat** [comment]
Nope. "Save data is corrupted"

**Comment by yellows8** [comment]
You're using the wrong cardid(README).

**Comment by lukeycat** [comment]
What should i be doing different?

**Comment by OverlordZio** [comment]
I am getting the same issue, it just stops working and you go back to the main 3ds menu its very odd.

**Comment by truegamergirl** [comment]
same issue too, anyone have a solution? Ive googled for hours

**Comment by lukeycat** [comment]
I honestly never did get this to work i just bought a friends 3ds that was on 9 something firmware and used browserhax
