### ISSUE TITLE
OOT hack 

### ISSUE THREAD

**Issue by Coraje187** [yellows8/oot3dhax#34]
I used the oot hack on 9.2 3DS XL but in says  homebrew loading crashing back to home screen. It used to work on 10.6. I did change to the right one I think too POST5_U_12288_8203. Has anyone had this problem?

**Comment by yellows8** [comment]
12288 is not a valid Home Menu version, you want 11272.

**Comment by Coraje187** [comment]
OK thanks yellow8 got it working now. :)
