### ISSUE TITLE
No save file matching my payload?

### ISSUE THREAD

**Issue by Wolfman666** [yellows8/oot3dhax#37]
I have an Old 3DSXL which I'm planning on updating to the newest firmware in my region (10.7.0-32E) as I need to download some stuff from the Nintendo e-shop. I want to inject an OoT savefile using Powersaves as this is the method I've used on my current firmware (10.1.0-27E) and it works perfectly.

However, when I try to find my payload using smea's github, it's coming up with N3DS_E_24576_9221, which has no corresponding Powersaves save data. Does this mean that 10.7.0-32E is not currently supported? If so, when will there be support for it?

**Comment by yellows8** [comment]
https://github.com/yellows8/oot3dhax/releases/tag/03-01-16

**Comment by Wolfman666** [comment]
Thanks for the help (and the extremely quick reply), for some reason I hadn't been able to view that download before you linked it to me :/ Oh well, I've got it now and it has what I was looking for :)
