### ISSUE TITLE
Files for n3ds Japan version firmware 9.7.0-25J

### ISSUE THREAD

**Issue by orangefinal** [yellows8/oot3dhax#4]
Any chance you could please provide me with the compiled version of ocarina of time regionfour for a Japanese new 3ds with firmware 9.7.0-25J? Thanks.

**Comment by yellows8** [comment]
For savedatafiler / savedata FS writing?

**Comment by orangefinal** [comment]
Yes, please.

**Comment by yellows8** [comment]
Can't you build oot3dhax+regionFOUR yourself?(no additional dependencies required for this with the latter anymore, with my last commit)
