### ISSUE TITLE
eshop suck on yellow screen

### ISSUE THREAD

**Issue by ashkicker6** [yellows8/oot3dhax#42]
every time i boot up oot3ds hax and go to use the old or new eshop they get stuck on a yellow screen any help?

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn

**Comment by ashkicker6** [comment]
it still wont work it gets stuck on the yellow screen every time i try this is my first time doing this its on an old 3ds with oot3dshax on 10.7  the yellow screen only happens on old and new eshop
