### ISSUE TITLE
Missing bin

### ISSUE THREAD

**Issue by soulstarfury** [yellows8/oot3dhax#44]
Recently downloaded latest OoT .zip Seems to be missing N3DS_U_25600_usa_9221.bin which isthe one I need, Go figure. Any help?

**Comment by yellows8** [comment]
" latest OoT .zip" "missing N3DS_U_25600_usa_9221.bin" Sure doesn't sound like the latest archive...

**Comment by soulstarfury** [comment]
I downloaded "oot3dhax_rawsaveimages_haxpayloads_01-25-16" and I can't find "N3DS_U_25600_usa_9221.bin"

**Comment by yellows8** [comment]
https://github.com/yellows8/oot3dhax/releases *cough* "Latest Release" label *cough*

**Comment by soulstarfury** [comment]
That's the one I downloaded though

**Comment by yellows8** [comment]
"oot3dhax_rawsaveimages_haxpayloads_01-25-16" Is outdated and doesn't have the latest-release label......

**Comment by soulstarfury** [comment]
Ohh, okay, I see what you mean. Sorry, I thought the top result was the latest release. This is my first time on GitHub. This allows me to activate the Homebrew loading screen just fine but I get stuck when the bottom screen turns red. Any help there? Or a redirect to where I can get help?

**Comment by yellows8** [comment]
https://smealum.github.io/3ds/ "Preparing your SD card"
