### ISSUE TITLE
oot3dhax crash

### ISSUE THREAD

**Issue by kwas84** [yellows8/oot3dhax#45]
What am I doing wrong?
New 3ds on 10.7.
![image](https://cloud.githubusercontent.com/assets/18667842/14799229/c67ec0b2-0b3b-11e6-868c-2d15f7249cde.png)
After that 3ds main menu shows up.
Guy who sold me this game is sure hax is ok. He tested it on his 3ds.

**Comment by kakanot** [comment]
Having the same problem with the 10.7.0-32E

**Comment by OverlordZio** [comment]
Same issue here on 10.7.0-32U, tried getting this to work multiple times and tried different methods, keeps crashing and I get booted to the 3ds main menu as well.
