### ISSUE TITLE
backup file corrupt

### ISSUE THREAD

**Issue by pink222** [yellows8/oot3dhax#46]

**Comment by yellows8** [comment]
Not sure what you mean, and please move that from the issue-title into the actual post.

**Comment by pink222** [comment]
my daughter used this and then used power save to mod fire emblem fates and we lost the cartridges-when trying to load a backup of her game, the game said it was corrupt and deleted it-any way to get the new cartridge to accept this mod back-up file?

**Comment by pink222** [comment]
Sorry I am not very educated but need to help my daughter.  Okay, so she has a backup file In her powersave for fire emblem fates-(we lost the first cartridge and purchased a new cartridge today) she tried to load the backup file from the powersave and the game said the file was corrupt and deleted it-could anyone help?  she is devastated and does not want to start from scratch

**Comment by yellows8** [comment]
This doesn't really sound oot3dhax related, but anyway:
Since you probably only have a raw saveimage from the original gamecard and nothing else saved, there's really no way to transfer the savedata to the new gamecard.
