### ISSUE TITLE
problem with SAVE for old 3DS 10.7.32 E

### ISSUE THREAD

**Issue by loader34** [yellows8/oot3dhax#47]
the save for power saves isnt present for my 3DS version. please help me

**Comment by yellows8** [comment]
You must be using the wrong release-archive ...............

**Comment by loader34** [comment]
I  used the url from this http://smealum.github.io/3ds/ in ocarina of times version

**Comment by loader34** [comment]
but the package no contain my specific version

**Comment by loader34** [comment]
i found it but each time would restore it on my 3ds the game say "the files was coorupted"

**Comment by KaBombz** [comment]
I realize this may not be the most relevant issue, but just confirming that the current release-archive only contains payloads up to *hax 2.6 gamma, right?
I've been trying to install supermysterychunkhax, and this seems to be the issue

**Comment by yellows8** [comment]
Run sploit_installer to install {latest version}.

**Comment by KaBombz** [comment]
Thanks for the help, wish me luck getting oothax to run (and my hardmodding in the summer)

**Comment by loader34** [comment]
Thanks for help the haxx was installed
