### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by Skullgasher** [yellows8/oot3dhax#48]
I recently unintentionally updated my 3DS to the newest software without downloading the necessary robin payloads for my OoTHax. Atm, I have no way of accessing the Homebrew Launcher. On the website, it says that I can directly write a raw savegame image to my gamercard. How would I do that?

**Comment by yellows8** [comment]
v11.0 is not supported yet anyway.

**Comment by Skullgasher** [comment]
> v11.0 is not supported yet anyway.
I know, I'd checked the website to see if it had been updated. Is there any way for me to continue using th e Homebrew Launcher?

**Comment by yellows8** [comment]
If that was your only method for running \*hax payload, then no for now.

**Comment by Skullgasher** [comment]
>  If that was your only method for running *hax payload, then no for now

So I won't be able to write the raw savegame image to my gamercard either?

**Comment by yellows8** [comment]
That's pointless when "v11.0 is not supported yet anyway."

**Comment by Skullgasher** [comment]
In the future, when it will have been bypassed

**Comment by yellows8** [comment]
Datel Powersaves for example.

**Comment by Skullgasher** [comment]
I see, thanks for the help

**Comment by Skullgasher** [comment]
> Datel Powersaves for example.

I have an old 3DS that's at 8.1.0-19U. Any way I could get the Homebrew Launcher onto it?

**Comment by yellows8** [comment]
\*hax payloads only support >=v9.0, just update to >=v9.0 via some gamecard.

**Comment by Skullgasher** [comment]
Would my 3DS be updated to the newest firmware if I installed an update for Smash Brothers?

**Comment by KiraKing** [comment]
hi when will v11.0 be bypassed

**Comment by Skullgasher** [comment]
> *hax payloads only support >=v9.0, just update to >=v9.0 via some gamecard.

Alright, just updated my 3DS to v9.2.0-20U. Oot3Dhax is on my SD card but I couldn't find it after reaching the Homebrew Launcher. Do I need a later version to use Oot3Dhax? I used the sysUpdater to update my 3DS
