### ISSUE TITLE
v11.0 support

### ISSUE THREAD

**Issue by KiraKing** [yellows8/oot3dhax#49]
when r u going to bypass v11.0 so we can get on if we updated already

**Comment by yellows8** [comment]
@smealum said he would handle it.

**Comment by yellows8** [comment]
If @smealum / someone else doesn't update it first, I might end up doing it myself if it's not already done by a certain time... :|

**Comment by yellows8** [comment]
https://github.com/yellows8/oot3dhax#110033-support
