### ISSUE TITLE
LNA-CTR-AQEE-MDE compatability??

### ISSUE THREAD

**Issue by froid-san** [yellows8/oot3dhax#5]
I'm on 9.0.0-20 U firmware and tried to compile using make EXECHAX=2 FWVER=0x25 and also changed the region to US since my game is AQEE, but still unsure since it's MDE

it build fine and I was able to see the save file Haxxxxxx on the game and load, but upon pressing "A" the top screen flash with some texture and the bottom screen displays "An error has occurred. Hold down the POWER to turn off the power...etc etc.."

I used the payload you've supply on the "regionFOUR_oot3d_jpn_new3ds_v98" file and put it in the root of the SD card, cause I'm having trouble compiling regionfour

**Comment by yellows8** [comment]
" put it in the root of the SD card" READ THE README.

I don't know what "MDE" is.

**Comment by froid-san** [comment]
so the problem lies with my game version? the payload is on the root of the sd card when I first tested it and never moved it, I was just confirming.

**Comment by yellows8** [comment]
It is NOT supposed to be on the SD card, READ THE README.

**Comment by froid-san** [comment]
okay tried to reread it very carefully and got it... it but something off.. this screen appears so fast and gets back to the home screen, not giving me time to change carts or press start
![20150621_071344](https://cloud.githubusercontent.com/assets/12982148/8269666/2966bfe4-17e6-11e5-9771-ffdad6cba735.jpg)

**Comment by yellows8** [comment]
...Did you seriously run that payload from "regionFOUR_oot3d_jpn_new3ds_v98.zip", with the system-version *clearly* included in the archive filename, on a v9.0 system?

**Comment by froid-san** [comment]
I used the payload.bin from the "regionFOUR_oot3d_jpn_new3ds_v98.zip" but I used the oot3dhax_usa.bin I've complied and renamed to save00.bin on a v9.0 system

Ok.. I think I know the problem... I was using a payload made for new3ds...will study compiling the regionfour payload for o3ds

**Comment by yellows8** [comment]
You were running a v9.8 payload on a v9.0 3ds........

RegionFOUR doesn't support JPN v9.0 atm. For JPN support atm it has to be >=v9.2(since that's the version where all of the USA/EUR/USA homemenu bins match).

**Comment by profi200** [comment]
Just a note: oot3dhax not working with all cards is a stupid rumor. All cards contain *exactly* the same main NCCH so there is not difference at all exept maybe the update partition which doesn't matter.

**Comment by idgrepthat** [comment]
Strange, the payload intended for US old3ds 9.2, POST5_WEST_12288.bin, also has the "fast exit" bug, but the same save used on my US n3ds 9.8 works (N3DS_WEST_19456.bin works on it too at least). Was able to boot CN japan.

Can confirm that N3DS_WEST_12288.bin does not work on US n3ds 9.2. "An error has occured " prompt -- not black screen.

summary, all US
old3ds 9.2 fail
n3ds 9.2 fail
n3ds 9.8 pass

**Comment by yellows8** [comment]
Make sure you're on the very latest regionFOUR commit.

**Comment by idgrepthat** [comment]
Ok, that fixed everything. Thanks.

summary, all US
old3ds 9.2 pass
n3ds 9.2 pass
n3ds 9.8 pass
