### ISSUE TITLE
help

### ISSUE THREAD

**Issue by megapete4** [yellows8/oot3dhax#52]
doing zelda hack, using the powersave thing, replaceing the backup and it wont register the payload as the new backup

**Comment by yellows8** [comment]
Be more specific.

**Comment by megapete4** [comment]
I followed the directions for the power saves- backed up, replaced the name of the payload with the name of the back up, deleted the back up, went back to the power save app… then nothing, whenever I did that b4 it worked

**Comment by megapete4** [comment]
hey, just wanted to know if there was anything i could do, if theres anything to do, i cant seem to figure out the problem

**Comment by mmroos1983** [comment]
You have the wrong probably have the wrong save. Follow instructions on github. There a two card types with each a dozen saves and two dongle types in the archive. You need to have the exact one for your firmware. If you use powersaves from codejunkies you need the bin files.

**Comment by megapete4** [comment]
I made sure I got the most up to date everything and made sure I got the right save, files, etc. I followed the instructions to the dot: backed up the game through powersave, dragged the other app/ rop-bin to the powersave folder, replaced it's name with the name of the back up, deleted the back up, opened the powersave app again, instead of the name of the backup, the list is blank. Just to be clear this is all for ocarina

**Comment by mmroos1983** [comment]
'dragged the other app/ rop-bin to the powersave folder'
You need the save from the zip of Yellow8's repository. Not otherapp or ropbin.

**Comment by megapete4** [comment]
From the 3/01 zip? Would it work on 11.0 3ds update?

**Comment by mmroos1983** [comment]
From here....
https://github.com/yellows8/oot3dhax/releases/tag/06-26-16
And make sure you have the homebrew starter kit on the SD. Which instructions did you follow btw?

**Comment by megapete4** [comment]
I was following instructions that I stated in the previous comment, the one that was from the download of the 3/01 thing, the one right b4 this one, hadn't been on in a week or two so I didn't know this new one was up, I'll try it and see what happens

**Comment by megapete4** [comment]
Works now, thanks for the help
