### ISSUE TITLE
OOThax restarts 3ds instead of loading homebrew

### ISSUE THREAD

**Issue by Hikaru22** [yellows8/oot3dhax#54]
Using powersaves, I injected the POST5_U_25600_usa_9221 file to my game after renaming it to match the backup I made. I have the latest homebrew starter kit from smealum loaded onto the root of my 3ds SD card. I'm on old 3ds 11.0.0-33U. Every time I use open my game & press a button to launch homebrew, either my game locks up & has to be shut down or my system says there was an error & it has to restart. Am I doing something wrong or did I miss a step? I had this working perfect a few months ago. I thought all I needed to change was the injected save file. I have now changed everything because nothing is working. 
![2016-06-09 19 28 17](https://cloud.githubusercontent.com/assets/15041455/15950978/920cfc8e-2e79-11e6-815f-e80734a332ff.jpg)
![2016-06-09 19 29 42](https://cloud.githubusercontent.com/assets/15041455/15950975/9208a7b0-2e79-11e6-9288-49d2a00f6807.jpg)
![2016-06-09 19 31 33](https://cloud.githubusercontent.com/assets/15041455/15950977/92093720-2e79-11e6-9132-744823699ef7.jpg)
![2016-06-09 19 35 31](https://cloud.githubusercontent.com/assets/15041455/15950976/92090296-2e79-11e6-934b-cb10df0fc01d.jpg)

**Comment by yellows8** [comment]
"11.0.0-33" #49
