### ISSUE TITLE
Save data is corrupt.

### ISSUE THREAD

**Issue by Jerey71** [yellows8/oot3dhax#55]
I have followed all the instructions, but something's still wrong. whenever I start up the game with the save, the game says "Save data corrupted. Deleting save data". What have I done wrong? and how do I fix it?

**Comment by yellows8** [comment]
" If you don't know what the cardids for your gamecard are(these are included with what are commonly called "gamecard-unique headers"), just try either directory until one of them works without the game triggering a savedata-corruption error at boot."

**Comment by Jerey71** [comment]
could you please explain further. I'm sorry, but this is my first time getting in to anything like this.

**Comment by Jerey71** [comment]
Are you still there?

**Comment by yellows8** [comment]
README
