### ISSUE TITLE
Wont Work

### ISSUE THREAD

**Issue by Xanderfkz** [yellows8/oot3dhax#56]
I literally have tried everything and it still wont work. I have the new payload and everything. It just restarts thats all it does.

**Comment by yellows8** [comment]
System-version?

**Comment by knightrox** [comment]
Probably his 3DS is on 11.0 version. Same problem 
Do you know, when we will be able to access the HBL, using OOTHAX?
Regards, KnightRox

**Comment by yellows8** [comment]
#49

**Comment by Xanderfkz** [comment]
Still can't get if to work properly 
I'm on 11.0.0.33 USA 
On the new Nintendo 3DS

**Comment by yellows8** [comment]
"#49" ...
