### ISSUE TITLE
Please help me! (Payload?)

### ISSUE THREAD

**Issue by mmroos1983** [yellows8/oot3dhax#57]
Hello,

I am running FW11 on a NEW 3DS XL (EUR) I pulled N3DS_E_24576_9221.bin from the cardids_c2fe009000000000\eur folder and used powersaves to put it on my OOT3D card, The save works and loads. I know I need many tries to 'pull through'..

I unpacked the homebrew starter kit on the SD. So I have a 3ds folder and a boot file in the root. I never got it to work. I read everywhere that I also need a BIN file in the root of my SD. Is that correct? If so, where do I get it? What should it be named? There is no tutorial explaining this for my FW version anywhere. I only read that it can work on FW11.

Please help me yellows8!

Best wishes!

**Comment by yellows8** [comment]
#49
