### ISSUE TITLE
Please pass this to Smea

### ISSUE THREAD

**Issue by mmroos1983** [yellows8/oot3dhax#59]
On New 3DS firmware 11 EUR version with EUR version OOT3D cartridge there is something strange with the saves.
When I use the correct save but in stead of N3DS one I use the POST one, the hack works halfway about 1 in 6 times. With halfway I mean: it glitches out, goes black, shows some text for a second and suddenly I am back in the home menu. But with no error at all.

When I use the correct N3DS save it's impossible (after 50 tries) to even get the hack to load partially.

Maybe Smea can use this info to speed up the 11.0 oot3dhax process. The post save does something different that makes the hack load frequently enough to be usable. It probably does not pull entirely through because it is meant for the old 3DS. So I am also wondering if people owning that system also experienced that the hack still works for them 1 in 6 times. If not, then this behavior is very strange.

All in all, maybe I am on to something, maybe not. Still, hope it helps.

**Comment by yellows8** [comment]
...
