### ISSUE TITLE
back up save not the same size as the saveimages

### ISSUE THREAD

**Issue by red09** [yellows8/oot3dhax#61]
what should I do?

**Comment by yellows8** [comment]
You're probably comparing with the wrong directory...

**Comment by red09** [comment]
I went to users > (name) > powersaves3ds and I just bought the powersaves so there is no other file I could confuse it with and when I went to saveimages_powersaves as instructed the backup I have is 129 KB

**Comment by yellows8** [comment]
What's the *exact* byte sizes of the files you're comparing?

**Comment by red09** [comment]
oh I didn't realize I had to look at properties of the saveimages to get the exact byte but then when I look at my back up save in it's properties says 128 KB I think it just might be glitching though
