### ISSUE TITLE
oot3d still not working on european new 3ds on 11.0

### ISSUE THREAD

**Issue by kamikazilucas** [yellows8/oot3dhax#65]
i am using the new files that are supposed to work with 11.0 but it dosent it just says error occured and restarts the system, im doing everything right, can someone please update this

**Comment by yellows8** [comment]
If you mean the "... press A to reboot" message, then you must not really be using the latest oot3dhax.

**Comment by kamikazilucas** [comment]
i used the 24576 on the 26th of june file which is the latest version

**Comment by yellows8** [comment]
https://github.com/yellows8/oot3dhax#haxx-usage

**Comment by kamikazilucas** [comment]
i did all that with the file and thats what happened

**Comment by kamikazilucas** [comment]
i have the right payload and the file files so it dosent really make any sense

**Comment by yellows8** [comment]
Some people say spamming A-button while savefile is loading helps, but tbh it just worked fine for me with pressing A once it fully loaded.

**Comment by kamikazilucas** [comment]
its not the save file thats the problem its pressing the items button

**Comment by yellows8** [comment]
...... You're not supposed to do that any more. https://github.com/yellows8/oot3dhax/issues/65#issuecomment-231376198

**Comment by kamikazilucas** [comment]
oh, what are you supposed to do then

**Comment by yellows8** [comment]
README

**Comment by kamikazilucas** [comment]
silly me, thanks for your help
