### ISSUE TITLE
Save Manager 

### ISSUE THREAD

**Issue by Xanderfkz** [yellows8/oot3dhax#67]
For some reason the same manager in the homebrew wont let me import the save back into the game at all.. 
Help?

**Comment by yellows8** [comment]
Be more specific.

**Comment by Xanderfkz** [comment]
I am able to back up my monster hunter save but when i try to import it back to the game it says restoring save data... terminate called aftering an instance of Exception terminate called recursively 
It just keeps say that than it goes back to the homebrew main menu...

**Comment by yellows8** [comment]
File an issue @ the repo for that app.
