### ISSUE TITLE
An Error Has Occurred.

### ISSUE THREAD

**Issue by 1239145** [yellows8/oot3dhax#68]
I keep getting a dialogue with an error message "An error has occured. Please save your data in any software currently in use, and then restart the system". I'm using 11.0.0-33U with Post5_U_24576_9221.bin, with an SD Card inserted with the Homebrew Starter pack extracted to the root directory.

I would also like to pre-emptively apologize for my probable stupidity.

**Comment by yellows8** [comment]
https://github.com/yellows8/oot3dhax#haxx-usage

**Comment by 1239145** [comment]
I tried that, but it keeps crashing just the same way. Do I need the SD Card to be in a certain way?

**Comment by yellows8** [comment]
No... Did you really press A after savefile load?

**Comment by 1239145** [comment]
I get a "Searching for target", a glitched text that passes too quickly to read, and then "The homemenu ropbin is ready". Then it crashes and nothing happens..

**Comment by yellows8** [comment]
Then you selected the wrong payload. Are you really using an Old3DS?

**Comment by 1239145** [comment]
Yep.
I'm using the small old 3ds.

**Comment by yellows8** [comment]
POST5_U_25600_usa_9221.bin

**Comment by 1239145** [comment]
Red bottom screen, black top screen with 2 white pixels in the bottom left
Unresponsive.

**Comment by 1239145** [comment]
Thank you!
