### ISSUE TITLE
OoT3DHax running NinjHax 1.1b

### ISSUE THREAD

**Issue by thaikhoa** [yellows8/oot3dhax#7]
Hi yellow8,
Thanks for keep supporting 3ds scene. This is really not an issue. I'm just curious to know that whether you could implement NinjHax 1.1 to use with OoT3DHax? Smealum won't care to implement 1.1 anymore but 2.0.

Your OoT3DHax region four works perfecly with digital version on Nintendo's eShop.

Cheers.

**Comment by yellows8** [comment]
That's not going to happen unless someone besides myself/smea does it.

**Comment by thaikhoa** [comment]
Hope you will have a look at that in near future. Regards.
