### ISSUE TITLE
It works but it doesn't work

### ISSUE THREAD

**Issue by Veterax842** [yellows8/oot3dhax#70]
I've just tried 3 times to open homebrew launcher with oot. I've followed all that you have sayed to do, but when i press A to open Homebrew, it says that ropbin file is ready and it crashes and takes me to the 3ds main menu. Please tell me what i can do. Thank you for reading.

**Comment by yellows8** [comment]
Wrong payload.

**Comment by JBCDev** [comment]
That title

**Comment by Dazzozo** [comment]
( ͡° ͜ʖ ͡°)

**Comment by Veterax842** [comment]
It is't wrong payload, 'cause i've got 11.0.0-33e and i've used the right payload

**Comment by Thompsen13** [comment]
Same issue here. After pressing 'A', the luncher tries to find something and and throws me back to the 3ds main menu,
