### ISSUE TITLE
Can i use this with eu nintendo select version with r4 save dongle ?

### ISSUE THREAD

**Issue by the4anoni** [yellows8/oot3dhax#74]
Question in topic

**Comment by yellows8** [comment]
README

**Comment by the4anoni** [comment]
I cant find anything about "nintendo select" version (it was relased in june this year)

**Comment by yellows8** [comment]
"r4 save dongle" == "saveimages" directory, "nintendo select" works fine.

**Comment by the4anoni** [comment]
Thanks :)
