### ISSUE TITLE
question:will the old installer ever comeback or be updated

### ISSUE THREAD

**Issue by monkeyman4412** [yellows8/oot3dhax#75]
I can't for the mean time install raw save imges or power saves to oot for two reasons, 1st I don't have powersaves, 2nd for what ever reason svdt, jksavemanager do not work with oot, like at all, it just hangs into a yellow screen, and yes I'am on 11.0.0 usa version, so it would kind of be nice for the old installer to be updated, I do understand the possiblity it might no be possible due to 11.0 update

**Comment by yellows8** [comment]
#62
