### ISSUE TITLE
KOR version doesn't work

### ISSUE THREAD

**Issue by oot3Dkor** [yellows8/oot3dhax#78]
I've tested with sploit_installer_oot3d from Smea's starter kit. But It's not work properly for now I think.
First of all, sploit_installer does not recognize the KOR OoT 3D. (It just say, title missing)
So I have to boot with OoT 3D USA version, and install KOR payload (ex 10.6.0-27K) to USA cartridge.
Next, manually extract the save file (system.dat, save00.bin, payload.bin) via SDF, and inject save to KOR cartridge. And now 10.5.0-26K, and 10.6.0-27K payload for *hax ready.

Test console: O3DS 10.1.0-23K.
Luckily I had a two retail cartridge that contain the update 10.5.0, 10.6.0 each. 
and manually updated to 10.5.0/10.6.0-23K.
(If I'm not wrong, we don't need to care of last digit of version, right?)

Test with each payload save five times. but non of them let the boot HB menu.
When I read sign in game, it's just hanged/freezed game, and shows error and reboot console. 
No exception, same result.

For just in case, I had test with Basehaxx too, but It works well without any problem. (10.5.0/10.6.0 both)
I have no idea what's the problem, maybe my progress is wrong?
Or KOR version payload/*hax doesn't properly work yet?

**Comment by yellows8** [comment]
README
