### ISSUE TITLE
New 3DS Update Ver. 11.1.0-34

### ISSUE THREAD

**Issue by iiDarknessPheonix** [yellows8/oot3dhax#79]
Nintendo has released a new update that patges Homebrew so I want to know if u will make another pack with that version. Thank you in advance ^-^

**Comment by iiDarknessPheonix** [comment]
*patches

**Comment by yellows8** [comment]
There is an edit button fwiw...

" want to know if u will make another pack with that version. " https://github.com/smealum/ninjhax2.x/issues/14#issuecomment-246891475
