### ISSUE TITLE
V. 11.0.0-34U Error

### ISSUE THREAD

**Issue by FedangleBoy** [yellows8/oot3dhax#84]
When I press the A button in Link's treehouse, I go to the black screen with white text. It then says "The homebrew robpin is ready.", but then goes to the home screen with the message "An error has occurred. Please save your data in any software currently in use, and then restart the system." I am pretty sure that I don't have the wrong payload because I checked the name of it on smealum.github.io and downloaded the most recent save from here. Thanks if you can help me!

**Comment by yellows8** [comment]
That sysver from issue-title isn't right...

**Comment by FedangleBoy** [comment]
So sorry, I didn't realize that there was a 1 in the Version number. It's good now

**Comment by yellows8** [comment]
" It's good now" ?

**Comment by FedangleBoy** [comment]
It works now
