### ISSUE TITLE
"Homebrew ropbin is ready" then nothing

### ISSUE THREAD

**Issue by SSJRyu1** [yellows8/oot3dhax#85]
I could really use a hand with this if possible.  I am using a new 3ds running 10.7.0-32 put the contents of the current starter kit on the 3DS microsd card directly, and used the proper power saves file for new3ds 10.7.0-32 in the game with the power saves, I used N3DS_U_20480_usa_9221, it works all the way up to when the screen starts to go black and say "Homebrew ropbin is ready"  After that it stalls and goes to the home menu and says "An error has occurred.  Please save your data in any software currently in use, and then restart the system."  I can't seem to get it to finish going to the homebrew menu for some reason.

**Comment by yellows8** [comment]
Wrong payload. N3DS_U_25600_usa_9221.bin

**Comment by SSJRyu1** [comment]
Awesome man, thanks for the help, it launched the homebrew properly now.  I am installing CFW for the first time so I may be back lol.

**Comment by yellows8** [comment]
"installing CFW for the first time so I may be back" <- This is not the place for support with that.
