### ISSUE TITLE
OOT3HAX O3DSXL Yellow bottom screen once running sploit

### ISSUE THREAD

**Issue by Qyogii** [yellows8/oot3dhax#89]
Hello i'm new to this Haxing thing, tbh I'm Surprised I was even able to launch  Homebrew. I'm running firm ware 11.1.0-34 U, my problem is once I've launched and try to start up the OOT3D sploit it's looks as if it start then nothing the top screen stays black while after the bottom switched from red and some other colors it stops at yellow then just sits there if this issue was already posted i apologize.

**Comment by yellows8** [comment]
If hbmenu doesn't boot then you used the wrong \*hax payload.

**Comment by Qyogii** [comment]
i tried the other one it doesn't work :/ this is what's going on here  https://www.youtube.com/watch?v=8bSgS3rWTm4&feature=youtu.be

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/issues/213
