### ISSUE TITLE
11.2 support

### ISSUE THREAD

**Issue by chrismslist** [yellows8/oot3dhax#90]
Does OOT3d hax work with 11.2? If so when is it coming out?

**Comment by yellows8** [comment]
Same as v11.1.....

**Comment by My1** [comment]
so it just works? great

**Comment by the4anoni** [comment]
I can test oot3dhax on new 3ds with official firmware 11.2 (non a9lh) ,when i get Ocarina of time 3and r4i save dongle (write to me after about 3 weeks)

**Comment by devonsoft** [comment]
I can't seem to get 11.2.035 to work using power saves. N3DS_U_26624_usa_9221.bin in c2fe just returns to main menu on new 3ds. 45fe says its corrupt so I think c2fe is the right one but it just crshes to 3ds menu and restarts.

**Comment by My1** [comment]
okay that's weird on my 11.2-35E it works.

**Comment by devonsoft** [comment]
Nevermind, it seems that it will just crash to the main menu if I don't wait for Link's green healthbar thing to get to full :/ . Sorry I was pressing A too quickly and that caused all my issues. It's working on my 11.2 now with N3DS_U_26624_usa_9221.bin

**Comment by TheProvider0** [comment]
@yellows8 I need help on installing oot3dhax on my digital copy of oot. I've gotten very close to being able to get it installed on it. The error Im getting is clipped to this post. Any ideas on how to fix it? I'm using a New 3DSXL on ver 11.2.0-35 USA. I use smashhax to get into homebrew launcher.
![20161130_180412](https://cloud.githubusercontent.com/assets/24284011/20779167/9112a6da-b727-11e6-9f1f-ec59d6804452.jpg)

**Comment by udelgadochio** [comment]
I installe oot3dhax through sploit installer and I just keep getting the "An error has ocurred, forcing the software to close. The system will now restart." screen, what am I doing wrong? I am on New 3ds XL with Luma and a9lh, 11.2.0-35U
